language: node_js

sudo: required

script:
  - npm install
  - npm test
  - ./node_modules/.bin/jest --coverage

after_script:
  - ./node_modules/.bin/codecov

node_js:
  - 7
notifications:
  slack:
    secure: SjpE2XojEgeXqOyCCy+k6WvEF9HiwXtGGgFOv34CKJjOevCTYz7NkC6vhUPNU9WYIw3K2JB36MyGEKCNFQY3YW78lZ9xDTUM45qJlVm4IwNZw37F+HEe3Snu4sISQwmyNHEmIybyaJSqvfnAwVLj7jxe3T96eQW0yUH/rzCNtVZXuO2t7ePVCAGIgNQG0F6iiuVPJ8PYj1XjvVckw+lGxbnNNrzqERVLAGMfxRR6va3o2PMVZVae9Uqec7kxr09WpzOFn0bxx7xOLtwdFG7TKlaIOm2wCpqDW1dDUQLzGfhEgmSzj4KMv++6vOqqbkX44p2mlqtT1GjkZk0J7H22Elu41GzJnOO+IDcK9gIMBTOVtuE4zeg7WHGPH9ZT6Wzp5H2WaxqemYxD1R/miPFn3K3Y6cmiitTHgwNOHGrWjowqSWJF9vz0XXOcgbpAFNJuVEzJffuZM+a+3zCJ+oiAZIGWe/lfE5QTdlpvXEU/2jAg8Lz1HbJYnnRgicosoKWr4igaCWR775RaFLephyppa8ubRKZPPm0W9yaebsS5zMPoHRA5jsqisHvudmb7jYw0ZSNiTVmrrD2wcORCpFh4uSLcnFV6Y9jyaQ8b6RwdKkmIilNBKPzDdPaM/m+T71Y0YQTTrP7GWoGfXYH0lI2wPyBeSj1LhQm36ocfl9fFH4o=

